### ISSUE TITLE
[Feature Request] Integrate on Goerli

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [zeropoolnetwork/zeropool-frontend#174]
In view of the recent change introduced by ethereum to it's testnet ecosystem, will it be possible that project will have Goerli testnet support soon ?

**Comment by antonpegov** [comment]
Hello @SyedMuhamadYasir, we have this in our future plans, but not in the next few months. Probabely we will start working on this integration after Eth 2.0 oficiall start.

**Comment by antonpegov** [comment]
Hello @SyedMuhamadYasir, due to Kovan test network deprivcated from 1/09/2022, we switched to the Goerli test network yerstaday.
