### ISSUE TITLE
Incoming transaction history items displayed as outgoing

### ISSUE THREAD

**Issue by crfergus** [zeropoolnetwork/zeropool-frontend#197]
Reproduction steps:
1. Make a transfer, i.e. public -> private.
2. View history on both accounts.

3. Receiver view:
![image](https://user-images.githubusercontent.com/102185709/199262688-62a3e843-31f7-4843-b536-fc233ee46129.png)

4. Sender view:
![image](https://user-images.githubusercontent.com/11507518/199262980-20154f94-f6cc-4e7e-85ca-5e2aad3e1659.png)

**Comment by antonpegov** [comment]
![image](https://user-images.githubusercontent.com/11507518/199325563-40ef2812-ee34-4a84-9af9-f6f97af4c4a0.png)

**Comment by antonpegov** [comment]
![image](https://user-images.githubusercontent.com/11507518/199456209-1099522b-8bbd-4725-9251-7286bdb13eab.png)
