### ISSUE TITLE
Incorrect public balance calculation on Near testnet

### ISSUE THREAD

**Issue by crfergus** [zeropoolnetwork/zeropool-frontend#201]
Some actions result in incorrcet displayed balance.

Reproduction steps:
1. Create new Near testnet account
2. Authorize, public balance should be equal to 199.99..
3. Deposit 50 tokens
4. Displayed public balance is 99.99.. , private palace is 50
5. Displayed public balance after balance update is 149.99..

**Comment by voidxnull** [comment]
Fixed in zeropoolnetwork/zeropool-client-js@b326bd98af35cb0b6472bf1e0f666f9fdc3aa4d8
