### ISSUE TITLE
Error getting public history

### ISSUE THREAD

**Issue by crfergus** [zeropoolnetwork/zeropool-frontend#236]
Near account id: fgjhkfdfxc.testnet
Seed phrase : involve filter bread quality brief power almost end range outer slot trade

Requesting history results in:

• UI Message:
"Error getting public history"

• Console output:
Error: Invalid character
    at n (bn.js:6:21)
    at u (bn.js:274:7)
    at o._parseBase (bn.js:298:14)
    at o._init (bn.js:105:14)
    at new o (bn.js:39:12)
    at t.formatNearAmount (format.js:31:23)
    at r.<anonymous> (client.ts:187:14)
    at l (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)

• Response body:
{
    "txns": [
        {
            "receipt_id": "Fn8fDAYHf527hE3CLuKyKnD4ckWMjpHLpHVPF5BB1aWD",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "4gCmqewz2nkVPvk56UdA3aYKtsTYqKpzY8bW5WVAMFwt",
            "included_in_block_hash": "13ny7vtNLoBK14T54M8HUZGXWp8gaH2xXH7Vi57iiUjR",
            "block_timestamp": "1693482514729952913",
            "block": {
                "block_height": 136224987
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 3e+25
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 724119012728300000000
            },
            "logs": []
        },
        {
            "receipt_id": "7Sanc1meZiZ5XMa9QXvtZUwFtppDfx5GFq7VFsgBwJU8",
            "predecessor_account_id": "fgjhkfdfxc.testnet",
            "receiver_account_id": "dev-1661448004647-22119316229252",
            "transaction_hash": "4gCmqewz2nkVPvk56UdA3aYKtsTYqKpzY8bW5WVAMFwt",
            "included_in_block_hash": "13ny7vtNLoBK14T54M8HUZGXWp8gaH2xXH7Vi57iiUjR",
            "block_timestamp": "1693482514729952913",
            "block": {
                "block_height": 136224987
            },
            "actions": [
                {
                    "action": "FUNCTION_CALL",
                    "method": "lock"
                }
            ],
            "actions_agg": {
                "deposit": 3e+25
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 724119012728300000000
            },
            "logs": []
        },
        {
            "receipt_id": "BepSAu5KArXQ2q5XDf4iXkN8oqRNqH6UMAx6kGzNEUP2",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "2THfDxzez43iawGdH6ABxgHKJZeBPFK5tRcNcwpEnDDq",
            "included_in_block_hash": "88Afq6roiwCrAJcFyK1d9YxabEWCDwrdDQqeRtCVZriC",
            "block_timestamp": "1691764116399907810",
            "block": {
                "block_height": 134594167
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 2e+25
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 724119012728300000000
            },
            "logs": []
        },
        {
            "receipt_id": "3mTC475pbPrQdTFvMdeVyeWCUALNxhBjkfu5EpgrSrBV",
            "predecessor_account_id": "fgjhkfdfxc.testnet",
            "receiver_account_id": "dev-1661448004647-22119316229252",
            "transaction_hash": "2THfDxzez43iawGdH6ABxgHKJZeBPFK5tRcNcwpEnDDq",
            "included_in_block_hash": "88Afq6roiwCrAJcFyK1d9YxabEWCDwrdDQqeRtCVZriC",
            "block_timestamp": "1691764116399907810",
            "block": {
                "block_height": 134594167
            },
            "actions": [
                {
                    "action": "FUNCTION_CALL",
                    "method": "lock"
                }
            ],
            "actions_agg": {
                "deposit": 2e+25
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 724119012728300000000
            },
            "logs": []
        },
        {
            "receipt_id": "8bx1Gfmi2mk3fvpQHYKivF1XDRe88a9PfgLk54iLqmBL",
            "predecessor_account_id": "llldkdjjs.testnet",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "884uapagKw9JsRLzhSx4vPCXKUM8kuYj2feW1eRChcC",
            "included_in_block_hash": "BKSTTTp3uKvG1bEMVHT93WHTNmKFxaodcDqhtUcAvJxC",
            "block_timestamp": "1691761068742422002",
            "block": {
                "block_height": 134589722
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 3853055179640978
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 44636512500000000000
            },
            "logs": []
        },
        {
            "receipt_id": "48incAjG15PQLB3o8UV9W1LJb4EJt9D8SzhvjecFYQSE",
            "predecessor_account_id": "llldkdjjs.testnet",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "7fx5DmETLpdZwJXuTBPVWVhEZG6DcmmE7gvCewv1DSDE",
            "included_in_block_hash": "5hBXYh2mVQbR7Gm6VMPvymziGWkcwiJ8K7cThoVntqie",
            "block_timestamp": "1691761040574770883",
            "block": {
                "block_height": 134589682
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 3853055179640978
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 44636512500000000000
            },
            "logs": []
        },
        {
            "receipt_id": "DEbvVLYEACvqs7NYoo8TL3QAtC8r7sQ5uZyj1WMyobvx",
            "predecessor_account_id": "dev-1661448004647-22119316229252",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "H7xJ1EbH9TbzPZhwDSMRPUmYPYj1iDWZmsXcjqJDTjHb",
            "included_in_block_hash": "7jBZ5Kagn5Goqnfwi2ksZd8mF98whdgBQZ1n3hE54zw7",
            "block_timestamp": "1691761036726415326",
            "block": {
                "block_height": 134589678
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 0
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 7.8363648259871e+21
            },
            "logs": []
        },
        {
            "receipt_id": "9xn9bqLzP9nhMENnBFuVfB6Jt2Jxz73qoW9oN8fxXZyf",
            "predecessor_account_id": "dev-1661448004647-22119316229252",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "7ViJtZu9LvMf4FBgw8AqbXVbzrcBryTm7qZ4mPi33DR5",
            "included_in_block_hash": "DGcC1pTNw1WuEvPR3fNj4w3CwtrxghxemtbmiCCTJd2D",
            "block_timestamp": "1691760999205853780",
            "block": {
                "block_height": 134589621
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 0
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 7.931090809169e+21
            },
            "logs": []
        },
        {
            "receipt_id": "GBJW5ZRQuGKCDgmGrckXHP8F7j62hmqneWnNmDJTJ6VJ",
            "predecessor_account_id": "dev-1661448004647-22119316229252",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "7rZsBrkHYaAEnPv6zSnJbtfAVdDSbX5QNgnJYzkR7mzy",
            "included_in_block_hash": "34mAg5KKtNNnUtrRoqBSvnoaKhS4p7WgBNSXT1RxE2xw",
            "block_timestamp": "1691760947671305118",
            "block": {
                "block_height": 134589547
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 0
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 7.965830222915e+21
            },
            "logs": []
        },
        {
            "receipt_id": "HJxoTm25qqCgKsWcxnceroTfphzLkyT7RAgUNQbCR8UY",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "9VRi3QBPgearhH8G2JZugdysbf8cifeN8x7pJAhCXrPj",
            "included_in_block_hash": "9fdm7ywXZJPTKwfYZkfa853hFB2uHF12c3coPRkppQWE",
            "block_timestamp": "1691760841892051288",
            "block": {
                "block_height": 134589395
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 2e+25
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 724119012728300000000
            },
            "logs": []
        },
        {
            "receipt_id": "5m3VdGwVQpKbocE5LUSUzQh7HgWQcucLt7nNB38Gn5pH",
            "predecessor_account_id": "fgjhkfdfxc.testnet",
            "receiver_account_id": "dev-1661448004647-22119316229252",
            "transaction_hash": "9VRi3QBPgearhH8G2JZugdysbf8cifeN8x7pJAhCXrPj",
            "included_in_block_hash": "9fdm7ywXZJPTKwfYZkfa853hFB2uHF12c3coPRkppQWE",
            "block_timestamp": "1691760841892051288",
            "block": {
                "block_height": 134589395
            },
            "actions": [
                {
                    "action": "FUNCTION_CALL",
                    "method": "lock"
                }
            ],
            "actions_agg": {
                "deposit": 2e+25
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 724119012728300000000
            },
            "logs": []
        },
        {
            "receipt_id": "CU7fgRPCrgMPJjruyp7t6tMyu4E8ihZULgk2DQVcDr75",
            "predecessor_account_id": "dev-1661448004647-22119316229252",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "321ufco8bShJ8nDwQT7awKni51ssZuxV7gP1khy1G5HS",
            "included_in_block_hash": "9ezVdxAAE6cTagmhJ58q5kCgRA8dZDcnMidvNTnZbCNA",
            "block_timestamp": "1691760685525218245",
            "block": {
                "block_height": 134589160
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 0
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 7.7976087356687e+21
            },
            "logs": []
        },
        {
            "receipt_id": "AA6VizaSXo36EZB3EVekx2g2WwNK9fEePpvMMd6CNnM8",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "4SSCgn9VQj1hfKLksoeXytpzrrB4JGAESS9VQdosaFUA",
            "included_in_block_hash": "GhNd9WjjPhDXzGRXodBSWLwwGSMm2nQ3RFh7L9knZMzc",
            "block_timestamp": "1691760633018364468",
            "block": {
                "block_height": 134589079
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 4e+25
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 725729208320900000000
            },
            "logs": []
        },
        {
            "receipt_id": "H9uusNbWaABLjEEh2Ge7AJjiL8Y4psrfkFtkDYpsEfvr",
            "predecessor_account_id": "fgjhkfdfxc.testnet",
            "receiver_account_id": "dev-1661448004647-22119316229252",
            "transaction_hash": "4SSCgn9VQj1hfKLksoeXytpzrrB4JGAESS9VQdosaFUA",
            "included_in_block_hash": "GhNd9WjjPhDXzGRXodBSWLwwGSMm2nQ3RFh7L9knZMzc",
            "block_timestamp": "1691760633018364468",
            "block": {
                "block_height": 134589079
            },
            "actions": [
                {
                    "action": "FUNCTION_CALL",
                    "method": "lock"
                }
            ],
            "actions_agg": {
                "deposit": 4e+25
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 725729208320900000000
            },
            "logs": []
        },
        {
            "receipt_id": "cQ4sZKPmcV9GHaD7G8kBTSGxZZhJ1nKjDzNj6qFZvyJ",
            "predecessor_account_id": "dev-1661448004647-22119316229252",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "pK82GKv5YkjtL2iQAFicL97pzFnzm19rJ9w8vNsX5Pg",
            "included_in_block_hash": "CGSzfVZ3rvze33RYiNi1a6buhie1pYxrDiSmqELcoCGN",
            "block_timestamp": "1691743183400277113",
            "block": {
                "block_height": 134565406
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 0
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 7.6945704290798e+21
            },
            "logs": []
        },
        {
            "receipt_id": "e2Yjt21utZcS4fgFusENUZDppHYzYmcXsi6k3Gnov6w",
            "predecessor_account_id": "fgjhkfdfxc.testnet",
            "receiver_account_id": "dev-1661448004647-22119316229252",
            "transaction_hash": "DiCoYxAYorSeybk6QQ52QkpDSbsZqeeMD9x3RSLT6hd3",
            "included_in_block_hash": "22zjXLSXbmFHuw4DyztoipWBF2bHXrYKYVHFRuRWmC87",
            "block_timestamp": "1691743068664930205",
            "block": {
                "block_height": 134565331
            },
            "actions": [
                {
                    "action": "FUNCTION_CALL",
                    "method": "lock"
                }
            ],
            "actions_agg": {
                "deposit": 1e+26
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 687800483782600000000
            },
            "logs": []
        },
        {
            "receipt_id": "3UaFDPBkHYVt2kxtToT554ixqoZ45pGZpvjKp7koyAru",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "DiCoYxAYorSeybk6QQ52QkpDSbsZqeeMD9x3RSLT6hd3",
            "included_in_block_hash": "22zjXLSXbmFHuw4DyztoipWBF2bHXrYKYVHFRuRWmC87",
            "block_timestamp": "1691743068664930205",
            "block": {
                "block_height": 134565331
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 1e+26
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 687800483782600000000
            },
            "logs": []
        },
        {
            "receipt_id": "FMEqKnFEAEFUAv1gceDvJkx7ZrML4zMkCupqzkT61DEL",
            "predecessor_account_id": "fgjhkfdfxc.testnet",
            "receiver_account_id": "dev-1686589568661-43655342590399",
            "transaction_hash": "6zbB3At8XpkWVVyZhRDjN4RmGZdsED5RqUPc3TvoXRXB",
            "included_in_block_hash": "HLjHKPWTPGuz7dwsZe5Vh8hCbGVjyPKV3BmwhLVYKSmx",
            "block_timestamp": "1687174483407366004",
            "block": {
                "block_height": 129519351
            },
            "actions": [
                {
                    "action": "FUNCTION_CALL",
                    "method": "ft_transfer_call"
                }
            ],
            "actions_agg": {
                "deposit": 1
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 1.8572899652164e+21
            },
            "logs": [
                "EVENT_JSON:{\\\"standard\\\":\\\"nep141\\\",\\\"version\\\":\\\"1.0.0\\\",\\\"event\\\":\\\"ft_transfer\\\",\\\"data\\\":[{\\\"old_owner_id\\\":\\\"fgjhkfdfxc.testnet\\\",\\\"new_owner_id\\\":\\\"zeropoolft2.voidxnull3.testnet\\\",\\\"amount\\\":\\\"500000000\\\"}]}"
            ]
        },
        {
            "receipt_id": "3VBVGj4ucPWCS2C28WZ1DoN5ajJcwD4P974SvcrD6y2L",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "6zbB3At8XpkWVVyZhRDjN4RmGZdsED5RqUPc3TvoXRXB",
            "included_in_block_hash": "HLjHKPWTPGuz7dwsZe5Vh8hCbGVjyPKV3BmwhLVYKSmx",
            "block_timestamp": "1687174483407366004",
            "block": {
                "block_height": 129519351
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 1
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 1.8572899652164e+21
            },
            "logs": []
        },
        {
            "receipt_id": "HbEFtNNAePvvDmkvNA9ZG8v8MSGavK7BrUU7RpAL3ihQ",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "6zbB3At8XpkWVVyZhRDjN4RmGZdsED5RqUPc3TvoXRXB",
            "included_in_block_hash": "HLjHKPWTPGuz7dwsZe5Vh8hCbGVjyPKV3BmwhLVYKSmx",
            "block_timestamp": "1687174483407366004",
            "block": {
                "block_height": 129519351
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 1
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 1.8572899652164e+21
            },
            "logs": []
        },
        {
            "receipt_id": "CKxxCb2aZ5qQSWXYn8MHvZg2Vn5iGcMSmn3WeG2KXNwu",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "6zbB3At8XpkWVVyZhRDjN4RmGZdsED5RqUPc3TvoXRXB",
            "included_in_block_hash": "HLjHKPWTPGuz7dwsZe5Vh8hCbGVjyPKV3BmwhLVYKSmx",
            "block_timestamp": "1687174483407366004",
            "block": {
                "block_height": 129519351
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 1
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 1.8572899652164e+21
            },
            "logs": []
        },
        {
            "receipt_id": "HcoHHAxjp73bjZJ7TkYtDeZW9xJhZsXHJ7qNV6TfmMy3",
            "predecessor_account_id": "fgjhkfdfxc.testnet",
            "receiver_account_id": "dev-1686589568661-43655342590399",
            "transaction_hash": "ECY7f2Jn91WQnwNBqppN6mMWyocNboSAXt5oGdZnygiu",
            "included_in_block_hash": "HQd49S5ug4aLXwVWCNyYfaG6eR62BaWATxPhqL56qWxK",
            "block_timestamp": "1687174140447190912",
            "block": {
                "block_height": 129519086
            },
            "actions": [
                {
                    "action": "FUNCTION_CALL",
                    "method": "storage_deposit"
                }
            ],
            "actions_agg": {
                "deposit": 1.25e+21
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 582625990066600000000
            },
            "logs": []
        },
        {
            "receipt_id": "2Zf8b8pdLyCWcDNJ8gcQaRqM9bvdyhVfnq3d54WsnnTy",
            "predecessor_account_id": "system",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "ECY7f2Jn91WQnwNBqppN6mMWyocNboSAXt5oGdZnygiu",
            "included_in_block_hash": "HQd49S5ug4aLXwVWCNyYfaG6eR62BaWATxPhqL56qWxK",
            "block_timestamp": "1687174140447190912",
            "block": {
                "block_height": 129519086
            },
            "actions": [
                {
                    "action": "TRANSFER",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 1.25e+21
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 582625990066600000000
            },
            "logs": []
        },
        {
            "receipt_id": "EfUg3pFhatcyEdzMyz7kB2KkEb7GwDgeBYFjMUNLSXJ",
            "predecessor_account_id": "fgjhkfdfxc.testnet",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "2UFHA4C7FHK3Mnnwf9YLcN9vNDN7PqhLHPaSdAsogZR2",
            "included_in_block_hash": "7ndYFanyYVCN4tBchfLTHLBSBSpvLGYnvXETzBJd9F13",
            "block_timestamp": "1687174103427958351",
            "block": {
                "block_height": 129519053
            },
            "actions": [
                {
                    "action": "ADD_KEY",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 0
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 41964925000000000000
            },
            "logs": []
        },
        {
            "receipt_id": "FyNcxCYRTkwWdP2iN9Z3bue9fN9zLqvzWMWC6zfrVfPs",
            "predecessor_account_id": "testnet",
            "receiver_account_id": "fgjhkfdfxc.testnet",
            "transaction_hash": "8VyHTtNn3RQa5d1nQDHHoBYWV3c9iS1qFyUPvQ76VSb3",
            "included_in_block_hash": "9x36SjYg4SQ7JKxgMmrYxYe5Q7gzwqofAipwFCL8AMnn",
            "block_timestamp": "1687174090956815171",
            "block": {
                "block_height": 129519042
            },
            "actions": [
                {
                    "action": "CREATE_ACCOUNT",
                    "method": null
                },
                {
                    "action": "TRANSFER",
                    "method": null
                },
                {
                    "action": "ADD_KEY",
                    "method": null
                }
            ],
            "actions_agg": {
                "deposit": 2.00000001e+26
            },
            "outcomes": {
                "status": true
            },
            "outcomes_agg": {
                "transaction_fee": 834989537500000000000
            },
            "logs": []
        }
    ]
}

**Comment by antonpegov** [comment]
Fixed
